language: php

php:
 - 5.6
 - 7.1
 - 7.2

matrix:
  allow_failures:
   - php: 7.1
   - php: 7.2

install:
 - composer selfupdate
 - composer install --dev
<<<<<<< HEAD

script:
 - ./vendor/bin/phpcs -p --standard=PHPCompatibility --runtime-set testVersion 5.4 --ignore=vendor/* .
 - ./vendor/bin/phpcs -s --ignore=vendor/* .
 - ./vendor/bin/php-cs-fixer fix --diff --dry-run

before_deploy:
- composer install --no-dev
- composer dump-autoload -o
=======
>>>>>>> develop
