language: php
php:
- '7.1'
script:
- composer install
- vendor/bin/phpcs -p ./ --standard=PHPCompatibility --runtime-set testVersion 5.3
before_deploy:
- composer install --no-dev
- composer dump-autoload -o